#!/bin/bash
#
# OpenEMR Root Files Cleanup Script
# Generated: 2026-01-16
#
# This script removes root-level files that are NOT needed for custom application.
# Total files to remove: 33
#

set -e  # Exit on error

OPENEMR_ROOT="/home/user/sacwan-openemr-mh"
cd "$OPENEMR_ROOT"

echo "=========================================="
echo "OpenEMR Root Files Cleanup"
echo "=========================================="
echo ""
echo "This will remove the following categories of files:"
echo ""
echo "SETUP/UPGRADE FILES (6 files):"
echo "  - setup.php (108K) - Installation wizard"
echo "  - acl_upgrade.php (54K) - ACL upgrade script"
echo "  - sql_upgrade.php (20K) - Database upgrade"
echo "  - sql_patch.php (4.9K) - Database patching"
echo "  - ippf_upgrade.php (6.2K) - IPPF upgrade"
echo "  - acknowledge_license_cert.html (24K) - License page"
echo ""
echo "DEVELOPMENT/CI CONFIG (19 files):"
echo "  - .composer-require-checker.json"
echo "  - .editorconfig"
echo "  - .shellcheckrc"
echo "  - .stylelintignore"
echo "  - .stylelintrc.json"
echo "  - build.xml (Ant build)"
echo "  - cloudbuild.yaml"
echo "  - codecov.yml"
echo "  - phpstan.neon.dist"
echo "  - phpunit.xml"
echo "  - phpunit.integration.xml"
echo "  - phpunit-isolated.xml"
echo "  - rector.php"
echo "  - rector-bootstrap.php"
echo "  - jest.config.js"
echo "  - eslint.config.mjs"
echo "  - gulpfile.js (OpenEMR frontend build)"
echo "  - docker-version"
echo "  - .gitmodules (obsolete - submodules deleted)"
echo ""
echo "LEGACY/UNUSED (8 files):"
echo "  - controller.php (legacy MVC - controllers/ deleted)"
echo "  - admin.php (multi-site admin - not needed)"
echo "  - clear_diagnosis_drafts.html"
echo "  - robots.txt (can recreate if needed)"
echo ""
echo "PRESERVED FILES:"
echo "  ✓ composer.json, composer.lock (PHP dependencies)"
echo "  ✓ package.json, package-lock.json (Node.js dependencies)"
echo "  ✓ index.php (main entry point)"
echo "  ✓ _rest_routes.inc.php (API routes)"
echo "  ✓ version.php (version info)"
echo "  ✓ .gitignore, .env.example"
echo "  ✓ LICENSE (legally required GPL)"
echo "  ✓ README.md (custom Mindline docs)"
echo "  ✓ DIRECTORY_ANALYSIS.md (custom)"
echo "  ✓ MINDLINE_PROJECT_DOCUMENTATION.md (custom)"
echo "  ✓ MIGRATION_NOTES.md (custom)"
echo "  ✓ ToDo.md (custom)"
echo "  ✓ cleanup_safe_directories.sh (custom)"
echo ""
echo "Total: 33 files to remove (~900KB)"
echo ""
echo "WARNING: This is permanent! Make a backup if unsure."
echo ""
read -p "Continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

echo ""
echo "Removing files..."

# Function to remove a file
remove_file() {
    local file="$1"
    if [ -f "$file" ]; then
        echo "  Removing $file..."
        rm -f "$file"
        echo "    ✓ Removed"
    else
        echo "  Skipping $file (not found)"
    fi
}

echo ""
echo "SETUP/UPGRADE FILES:"
remove_file "setup.php"
remove_file "acl_upgrade.php"
remove_file "sql_upgrade.php"
remove_file "sql_patch.php"
remove_file "ippf_upgrade.php"
remove_file "acknowledge_license_cert.html"

echo ""
echo "DEVELOPMENT/CI CONFIG:"
remove_file ".composer-require-checker.json"
remove_file ".editorconfig"
remove_file ".shellcheckrc"
remove_file ".stylelintignore"
remove_file ".stylelintrc.json"
remove_file "build.xml"
remove_file "cloudbuild.yaml"
remove_file "codecov.yml"
remove_file "phpstan.neon.dist"
remove_file "phpunit.xml"
remove_file "phpunit.integration.xml"
remove_file "phpunit-isolated.xml"
remove_file "rector.php"
remove_file "rector-bootstrap.php"
remove_file "jest.config.js"
remove_file "eslint.config.mjs"
remove_file "gulpfile.js"
remove_file "docker-version"
remove_file ".gitmodules"

echo ""
echo "LEGACY/UNUSED:"
remove_file "controller.php"
remove_file "admin.php"
remove_file "clear_diagnosis_drafts.html"
remove_file "robots.txt"

echo ""
echo "=========================================="
echo "Cleanup Complete!"
echo "=========================================="
echo ""
echo "Removed 33 unnecessary files successfully."
echo ""
echo "PRESERVED FILES:"
echo "  ✓ composer.json, composer.lock"
echo "  ✓ package.json, package-lock.json"
echo "  ✓ index.php"
echo "  ✓ _rest_routes.inc.php"
echo "  ✓ version.php"
echo "  ✓ .gitignore, .env.example"
echo "  ✓ LICENSE"
echo "  ✓ All custom documentation (README.md, etc.)"
echo ""
echo "Next steps:"
echo "  1. Test your application to ensure everything works"
echo "  2. Commit these changes to git"
echo ""
